name: coursebuddy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.2
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  file_picker: ^10.3.2
  url_launcher: ^6.3.0
  cloud_functions: ^6.0.0
  sign_in_button: ^4.0.1
  logger: ^2.0.2
  # pdf: ^3.11.0       # For creating PDF files
  printing: ^5.13.1
  device_info_plus: ^9.1.2
  firebase_analytics: ^12.0.1
  firebase_database: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/coursebuddy_logo.png
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
